### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by fr0der1c** [kkkisme/download-xiaoce#3]
```
$ npm start

> download-xiaoce@1.0.0 start /Users/frederic/Projects/download-xiaoce
> node app.js

/Users/frederic/Projects/download-xiaoce/app.js:29
async function load() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! download-xiaoce@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the download-xiaoce@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by fr0der1c** [comment]
OK. I found the problem. My Node version(v6.9.5) is too old. It doesn't support async function.

**Comment by fr0der1c** [comment]
However, it's still not working. It gets stuck with no output after running.
